### ISSUE TITLE
Content Migration

### ISSUE THREAD

**Issue by shsteimer** [hlxsites/stewart#1]

**Comment by badvision** [comment]
Round one import [1] was pretty successful but there are a few issues that need to be resolved or punted to follow-up work

1. Some style names need adjustment/translation
2. List content import is currently unsuccessful (this should be resolved with the list story since it's not a lot of content currently using it.  We might consider manually authoring it.)
3. Undefined labels show in a few places
4. Column blocks import incorrectly in some pages, and in other places where grids are used for sub-nav it results in errors on the page.
5. Forms content is not imported correctly.  A story for forms was created to address this.



[1] https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BAB853EAC-4218-413C-A895-325724D8DCC7%7D&file=import-report-General.xlsx&action=default&mobileredirect=true

**Comment by badvision** [comment]
Import round 2 [1] is a big improvement.  We should be ok to move forward now.

[1] https://adobe.sharepoint.com/sites/HelixProjects/Shared%20Documents/Forms/AllItems.aspx?FolderCTID=0x012000FF16C1F85E2B3849A4CD207A7190B18C&id=%2Fsites%2FHelixProjects%2FShared%20Documents%2Fsites%2Fstewart%2Dtitle%2Fdrafts%2Fbrobert%2FImport%20%2D%20General%20Content%20%2D%20take%202&viewid=124ad5f1%2D60ba%2D476c%2Dade8%2D7c1df274ee95

**Comment by badvision** [comment]
Some additional areas of needed improvement:
1. Get icons from source HTML
2. Get related footer links and capture as part of page metadata
3. Switch link block so 2-col is default and 1-col is the variant
4. Evaluate combinations of section styles and consider reducing to a simpler list of style variants.
5. Detect any hero styles/variants

**Comment by badvision** [comment]
Based on the general set of pages (first tab of url import spreadsheet) there are 24 combinations of styles used across 227 imported sections.  The correlation looks like this:
![image](https://github.com/hlxsites/stewart/assets/5144198/a81801ec-4126-4b7e-81a5-deb253fd2ee2)

The raw counts and style combinations are the following:
```
none	74
grey, no margin	28
dark background, high opacity, wide	1
narrow	5
no margin, teal	22
no margin, wide	2
teal	2
dark background, high opacity, no margin, overlay right, wide	1
grey	15
black, no margin	3
blue, no margin	2
dark background, medium opacity, no gradient	1
no margin	46
dark background, high opacity, no margin, overlay left	1
dark background, no gradient, no margin	5
blue	1
dark background, medium opacity, overlay right	4
wide	3
dark background, high opacity, no margin, overlay right	1
dark background, no gradient, no margin, ss-overlayopacity-50	5
dark background, medium opacity, no gradient, no margin	1
dark background, no gradient, ss-overlayopacity-50	2
dark background, no gradient, no margin, ss-overlayopacity-70	1
dark background, overlay right, ss-overlayopacity-50, wide	1
```

Hero styles are simpler with only 10 combinations:
dark background, low opacity	6
dark background, ss-margin-bottom-small, ss-overlayopacity-30	7
dark background, ss-overlayopacity-40	5
dark background, ss-margin-bottom-small, ss-overlayopacity-40	4
dark background, ss-margin-bottom-small, ss-overlayopacity-50	24
dark background, low opacity, ss-margin-bottom-small	3
none	18
dark background, ss-margin-bottom-small, ss-overlayopacity-40, no-background	1
dark background, ss-overlayopacity-50	1
no-background	2

It would be best for hero if "dark background" was assumed, and light background was used instead only where needed.
