### ISSUE TITLE
Landing page import

### ISSUE THREAD

**Issue by badvision** [hlxsites/stewart#20]
Currently landing pages are not implemented very well in the importer.  There are no sections or columns detected.  Also, landing pages have a very different format so this might require a special case flow entirely.  Some landing pages imported with sections but have some "untitled" labels in a few places.

For example:
- https://www.stewart.com/en/landing-pages/columbia-altogether-different.html

![image](https://github.com/hlxsites/stewart/assets/5144198/60f83046-3b01-4c64-a7a7-5037f60ebce0)

**Comment by badvision** [comment]
A lot of this may have been resolved by the rewrite to the column block import code, but it wasn't specifically tested against landing pages per se.

**Comment by badvision** [comment]
For this page (Columbia - We're altogether different) the following issues are present:
- Columns are not properly detected
- Footer should be different for landing pages (e.g any page using the template named 'landing-page-template')
- There is a video above the fold which should be a smaller size, and also needs manual re-authoring to add a preview image.  The logo at the top is being picked up instead and it doesn't look right.
- The content area should be a translucent white box and there is no section styling applied to do this.  Other landing pages may vary, but ultimately it requires importer improvements

**Comment by shsteimer** [comment]
@badvision 

Took a look at some of the landing pages, I think import can be improved, but some of this is just gonna take manual authoring touch ups, unfortunately, see #67. There are only 71 of them so may not be so bad.

Reagrdless of import or not, here are my thoughts:
* landing pages have no header (in template js, set a class no header. have scripts.js buildHeader detect this and adjust)
* most, but not all, have a simplified footer. use metadata.xlsx to set different footer content for the landing pages directory. update footer.js to read this content instead based on metadata prop
* Footer is also transparent and inherits bg color from last section on the page (do-able, but could get weird to make this happen)
* content is largely made up of existing blocks, and seems to take 1 of 2.5 forms
  * one large section with a background image and a card that has all the content in it https://www.stewart.com/en/landing-pages/puget-sound-ron.html
  * hero with sections following it https://www.stewart.com/en/landing-pages/mobility/mobility.html
  * some of the hero ones also have a card in subsequent content https://www.stewart.com/en/landing-pages/social-media-guide-for-real-estate-agents.html
* often/ but not always, there is a logo either in the hero or above the card, depending on the layout. since that logo isn't always the same, think this just need to be normal content.
